### PR TITLE
Fix NAMESPACE so it can be generated

### PR DESCRIPTION
**Pull request by dfrankow**
NAMESPACE has to have the "Generated by roxygen2" header. Not sure how it fell off.

### CODE REVIEW

**Comment by SteffenMoritz** [comment]
I already realized this, have it now in my own commit :)

Didn't know devtools::document() existed -  that is really nice - exactly what was needed.
I always hesitated  to use roxygen2, because I thought it is not possible to use it without transferring the manually created man pages to roxygen2 markup.

**Comment by dfrankow** [comment]
Gotcha. I think it skips things it hasn't generated, so you could move the pages one by one if you wished.

**Comment by SteffenMoritz** [comment]
Yeah that was the first thing I checked  - that the existing documentation stays there :)

After I merged the last updates:
0 errors, 0 warnings, 0 notes

On my own Mac
ass well on TravisCI https://travis-ci.org/github/SteffenMoritz/ridge

I now submitted to WinBuilder 
(https://win-builder.r-project.org/upload.aspx)
in order to check that for Windows everything is fine too.

**Comment by dfrankow** [comment]
Ah, gotcha, this is already on master. Thanks!

**Pull request closed without merging**
