### PR TITLE
Add nobs.ridgeLinear

### PR DESCRIPTION
**Pull request by dfrankow**
Like nobs.lm, number of observations.

### CODE REVIEW

**Comment by dfrankow** [comment]
This doesn't have to go in 2.5, or it can. Up to you.

**Comment by SteffenMoritz** [comment]
Ah sure we'll put it in there :)

The WinBuilder builds were all ok - also for the R dev version -  see e.g.:
https://win-builder.r-project.org/o6LtQ6AntgIv/00check.log

That's good (because sometimes CRAN adds new requirements, which you have to fix first before uploading a new version) which does not seem the case here. 

Let me try to add some test cases and then we upload on CRAN.
(but I'll also wait a moment, if you still want to add something)

**Comment by SteffenMoritz** [comment]
Ah ok, this merge actually introduced an error message for Travis-CI.
But nothing serious.

-----------------
Build #46 was broken2 mins and 43 secs
--Merge pull request #12 from dfrankow/dan_nobsAdd nobs.ridgeLinear
-----------------

I added a 
#' @importFrom stats nobs 
and now the error disappeared. 
(made a commit for this already)

**Comment by dfrankow** [comment]
Thanks!

**Pull request merged**
